image: node:18.18.0

variables:
  REPORT_FILENAME: gl-sast-report.json
  MAX_IMAGE_SIZE_MB: 54
  MAX_SCAN_DURATION_SECONDS: 30
  SAST_EXCLUDED_ANALYZERS: "eslint, nodejs-scan, semgrep"

stages:
  - sast
  - build
  - test
  - deploy

eslint:
  stage: sast
  script:
    - npm install eslint -g
    - npm install eslint-plugin-react@latest --save-dev
    - eslint .
  rules:
    - exists:
        - "package.json"

build:
  stage: build
  script:
    - npm run build
  rules:
    - exists:
        - "package.json"

test:
  stage: test
  script:
    - npm test
  rules:
    - exists:
        - "package.json"

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  rules:
    - exists:
        - "package.json"